api_server:
  http:
    cors:  
      enabled: True
      access_control_allow_origins: ["*"]
      access_control_allow_methods: [GET, OPTIONS, POST, HEAD, PUT]
      access_control_allow_credentials: True
      access_control_allow_headers: Null
      access_control_max_age: Null
      access_control_expose_headers: [Content-Length]
